python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 0 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 1 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 2 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 3 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 4 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 5 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 6 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 7 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 8 --n-runs 9
python indicator_draw_learning_graph.py --study-name entombed_cooperative_1_1e7_0 --parameter-id 9 --n-runs 9